// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tixdqgipsacxnfocsuxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpeGRxZ2lwc2FjeG5mb2NzdXhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NDQwNTQsImV4cCI6MjA2NTMyMDA1NH0.OzR4sGXoL2fCMnEbDbyNslgpkDGM_d5LSArAOs84MfA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);